name: Detect build difference

on:
  push:
    branches: [release, develop]
  pull_request:
    branches: [release, develop]
jobs:
  build-on-current-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}-current
          path: dist

  build-on-base-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - uses: actions/checkout@v3
        with:
          ref: develop
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}-base
          path: dist

  detect-build-diff:
    needs:
      - build-on-current-branch
      - build-on-base-branch
    outputs:
      diff-name-only: ${{ steps.diff-name-only.outputs.stdout }}
      diff-exit-code: ${{ steps.diff-name-only.outputs.exitCode }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}-current
          path: dist-current
      - uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}-base
          path: dist-base

      - id: diff-name-only
        uses: gh640/command-result-action@v1
        with:
          command: diff -qr dist-current dist-base
