name: Deploy on PR Merged to Develop

on:
  push:
    branches: [main]

jobs:
  if_merged:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: "16"
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Install dependencies
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
      - name: Upload to kintone
        run: |
          npx kintone-customize-uploader dest/customize-manifest.json --base-url $KINTONE_BASE_URL --username $KINTONE_USERNAME --password $KINTONE_PASSWORD
        env:
          KINTONE_BASE_URL: ${{ secrets.KINTONE_BASE_URL }}
          KINTONE_USERNAME: ${{ secrets.KINTONE_USERNAME }}
          KINTONE_PASSWORD: ${{ secrets.KINTONE_PASSWORD }}
